# https://results.pre-commit.ci/repo/github/821875747
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.5.1
  hooks:
    # Run the linter.
    - id: ruff
      args: [--fix]
      pass_filenames: false
    # Run the formatter.
    - id: ruff-format