repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # must match test-requirements.txt
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.1.1  # must match test-requirements.txt
    hooks:
      - id: black
        exclude: '^(test-data/)'
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.0  # must match test-requirements.txt
    hooks:
      - id: ruff
        args: [--exit-non-zero-on-fix]