# https://results.pre-commit.ci/repo/github/821875747
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.5.1
  hooks:
    # Run the linter.
    - id: ruff
      args: ["--fix"]
    # Run the formatter.
    - id: ruff-format


# -   repo: https://github.com/pycqa/isort
#     rev: 5.12.0
#     hooks:
#       - id: isort

  TODO clang-format
-  repo: https://github.com/pre-commit/mirrors-clang-format
   rev: v14.0.6 # TODO update with clang version
   hooks:
   -  id: clang-format
    args: ["--config", "src/float/.clangformat.yaml"]
