uint8 FLIR_FRONT = 0
uint8 FLIR_DOWN = 1

uint8 LUX_LEFT = 2
uint8 LUX_RIGHT = 3
uint8 LUX_LEFT_RECT = 4
uint8 LUX_RIGHT_RECT = 5
uint8 LUX_DISPARITY = 6
uint8 LUX_DEPTH = 7

bool on
uint8 cam
---
bool success